/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.management.timer.Timer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author claudio
 */
public class framePrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form framePrincipal
     */
    public framePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnVentas = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnAjusteStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClienteBus = new javax.swing.JButton();
        btnProductoBus = new javax.swing.JButton();
        btnVentasBus = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInventario = new javax.swing.JMenu();
        mnuCaja = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenu();
        mnuManproducto = new javax.swing.JMenu();
        MnuProducto = new javax.swing.JMenuItem();
        mnuManClientes = new javax.swing.JMenuItem();
        mnuProveedor = new javax.swing.JMenuItem();
        mnuManUsuarios = new javax.swing.JMenuItem();
        mnuAdministracion = new javax.swing.JMenu();
        mnuInformacion = new javax.swing.JMenu();
        mnuMinimizar = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        btnVentas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Desktop\\sistemaDeVentas2.0\\pistola.jpg")); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnCompras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCompras.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Desktop\\sistemaDeVentas2.0\\Cash-register-icon.png")); // NOI18N
        btnCompras.setText("COMPRAS");
        btnCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprasMouseClicked(evt);
            }
        });
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/camion.png"))); // NOI18N
        btnProveedor.setText("PROVEED");
        btnProveedor.setAutoscrolls(true);
        btnProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedorMouseClicked(evt);
            }
        });
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        btnInformes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInformes.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Desktop\\sistemaDeVentas2.0\\informes.png")); // NOI18N
        btnInformes.setText("INFORMES");
        btnInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInformesMouseClicked(evt);
            }
        });

        btnAjusteStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAjusteStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/Stock2.png"))); // NOI18N
        btnAjusteStock.setText("Stock");
        btnAjusteStock.setAlignmentY(0.2F);
        btnAjusteStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjusteStockMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 58)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Nemesis ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Compilacion A-132");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Reuz C.O.R.P  S.A");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("MANTENEDOR ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("BUSQUEDAS");

        btnClienteBus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClienteBus.setText("CLIENTE");
        btnClienteBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteBusMouseClicked(evt);
            }
        });

        btnProductoBus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProductoBus.setText("PRODUCTO");
        btnProductoBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductoBusMouseClicked(evt);
            }
        });

        btnVentasBus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVentasBus.setText("VENTAS");
        btnVentasBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasBusMouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("DETALLE-VENTA");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("PROVEEDORES");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("REPORTES");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("CLIENTE");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("VENTA");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("PRODUCTO");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("PROVEEDOR");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("USUARIO");

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/man24.png"))); // NOI18N
        jButton9.setText("MANTENEDORES");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        mnuInventario.setText("Inventario");
        mnuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuInventarioMouseClicked(evt);
            }
        });
        mnuInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInventarioActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuInventario);

        mnuCaja.setText("Caja");
        jMenuBar1.add(mnuCaja);

        mnuClientes.setText("Clientes");
        mnuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuClientes);

        mnuManproducto.setText("Actualizacion");
        mnuManproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuManproductoMouseClicked(evt);
            }
        });

        MnuProducto.setText("Mantenimiento Producto");
        MnuProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuProductoMouseClicked(evt);
            }
        });
        MnuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuProductoActionPerformed(evt);
            }
        });
        mnuManproducto.add(MnuProducto);

        mnuManClientes.setText("Mantenimiento Clientes");
        mnuManClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuManClientesMouseClicked(evt);
            }
        });
        mnuManproducto.add(mnuManClientes);

        mnuProveedor.setText("Mantenimiento Proveedor");
        mnuManproducto.add(mnuProveedor);

        mnuManUsuarios.setText("Mantenimiento Usuarios");
        mnuManUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuManUsuariosMouseClicked(evt);
            }
        });
        mnuManUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManUsuariosActionPerformed(evt);
            }
        });
        mnuManproducto.add(mnuManUsuarios);

        jMenuBar1.add(mnuManproducto);

        mnuAdministracion.setText("Administracion");
        jMenuBar1.add(mnuAdministracion);

        mnuInformacion.setText("F7 Informacion");
        mnuInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuInformacionMouseClicked(evt);
            }
        });
        mnuInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformacionActionPerformed(evt);
            }
        });
        mnuInformacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnuInformacionKeyReleased(evt);
            }
        });
        jMenuBar1.add(mnuInformacion);

        mnuMinimizar.setText("F8 Minimizar");
        jMenuBar1.add(mnuMinimizar);

        mnuSalir.setText("F12 Salir");
        mnuSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnuSalirKeyReleased(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton9))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClienteBus, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2))))
                    .addComponent(jLabel5)
                    .addComponent(btnProductoBus, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentasBus, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjusteStock)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjusteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClienteBus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProductoBus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVentasBus)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInventarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuInventarioActionPerformed

    private void mnuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInventarioMouseClicked
        // TODO add your handling code here:
       // mgb "Desea Salir del Sistema"
         dispose();
        setVisible(false);
    }//GEN-LAST:event_mnuInventarioMouseClicked

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnAjusteStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjusteStockMouseClicked
        frmProductoBus stockFrame = new frmProductoBus();
        stockFrame.setVisible(true);
        this.dispose();
       
       
        
    }//GEN-LAST:event_btnAjusteStockMouseClicked

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
 frmVentas VentasFrame = new frmVentas();
         VentasFrame.setVisible(true);   
         this.dispose();
    }//GEN-LAST:event_btnVentasMouseClicked

    private void btnComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMouseClicked
         VentasConFactura comprasFrame = new VentasConFactura();
         comprasFrame.setVisible(true); 
          this.dispose();
         
    }//GEN-LAST:event_btnComprasMouseClicked

    private void btnInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformesMouseClicked
        frmInformes informeFramee = new frmInformes();
         informeFramee.setVisible(true); 
          this.dispose();
    }//GEN-LAST:event_btnInformesMouseClicked

    private void mnuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuClientesMouseClicked
        // TODO add your handling code here:
      
        
        
    }//GEN-LAST:event_mnuClientesMouseClicked

    private void mnuManUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManUsuariosActionPerformed

    private void MnuProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuProductoMouseClicked
        // TODO add your handling code here:
      JOptionPane.showMessageDialog(this, "producto");
      
    }//GEN-LAST:event_MnuProductoMouseClicked

    private void MnuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuProductoActionPerformed

    private void mnuManUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuManUsuariosMouseClicked
        // TODO add your handling code here:
        frmUsuarios usuariosFrame = new frmUsuarios();
        usuariosFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuManUsuariosMouseClicked

    private void mnuManproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuManproductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManproductoMouseClicked

    private void mnuManClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuManClientesMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"clientes");
    }//GEN-LAST:event_mnuManClientesMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        FrmProveedorBus ProvFrame = new FrmProveedorBus();
        ProvFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        FrmDetalleVentaBus venDetalle = new FrmDetalleVentaBus();
        venDetalle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnVentasBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasBusMouseClicked
        // TODO add your handling code here:
        frmVentasBus ventasfrmbus = new frmVentasBus();
        ventasfrmbus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentasBusMouseClicked

    private void btnProductoBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoBusMouseClicked
        // TODO add your handling code here:
        frmProductoBus producbus = new frmProductoBus();
        producbus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductoBusMouseClicked

    private void btnClienteBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteBusMouseClicked
        // TODO add your handling code here:
        frmClienteBus frmCliBus  = new frmClienteBus();
        frmCliBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClienteBusMouseClicked

    private void mnuInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInformacionMouseClicked
        // TODO add your handling code here:
         try {
              Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"ayudita.pdf");
               System.out.println("Final");
                } catch (IOException e) {
// TODO Auto-generated catch block
            e.printStackTrace();
}
         
        
    }//GEN-LAST:event_mnuInformacionMouseClicked

    private void mnuInformacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuInformacionKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuInformacionKeyReleased

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void mnuSalirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuSalirKeyReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirKeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        frmIngresoRestringido mantenedor  = new frmIngresoRestringido();
        mantenedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
          addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
          addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_formWindowClosing

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorMouseClicked
        // TODO add your handling code here:
        FrmProveedorBus ProvFrame = new FrmProveedorBus();
        ProvFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProveedorMouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowStateChanged

    private void mnuInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new framePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuProducto;
    private javax.swing.JButton btnAjusteStock;
    private javax.swing.JButton btnClienteBus;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnProductoBus;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVentasBus;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuCaja;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuInformacion;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenuItem mnuManClientes;
    private javax.swing.JMenuItem mnuManUsuarios;
    private javax.swing.JMenu mnuManproducto;
    private javax.swing.JMenu mnuMinimizar;
    private javax.swing.JMenuItem mnuProveedor;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
