/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.detalleVenta;
import Controlador.producto;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author claudio
 */
public class FrmDetalleVentaBus extends javax.swing.JFrame {
producto P= new producto();
     private Connection con = null;
     private ResultSet rs = null;
     private Statement stmt= null;
     private ResultSetMetaData  rsm = null;
    
  
    /**
     * Creates new form FrmDetalleVentaBus
     */
    public FrmDetalleVentaBus() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPrecioBus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        btnCantidad = new javax.swing.JButton();
        BtnNumeroVenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jt1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jt1.setForeground(java.awt.Color.blue);
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Ingrese parametros de Busqueda");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Detalles de Consulta Actual");

        jButton5.setBackground(java.awt.Color.green);
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/impresora32.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTodos.setText("TODOS");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("BUSQUEDA DETALLE DE VENTA");

        btnPrecioBus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrecioBus.setText("PRECIO");
        btnPrecioBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecioBusActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("FECHA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/atras3.png"))); // NOI18N
        jButton4.setText("Volver");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMarca.setText("LIMPIAR");
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        btnCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCantidad.setText("VTA-CANTIDAD");
        btnCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadActionPerformed(evt);
            }
        });

        BtnNumeroVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnNumeroVenta.setText("NRO-VENTA");
        BtnNumeroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNumeroVentaActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/producto48.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Desde ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Hasta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnNumeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(btnTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrecioBus, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(250, 250, 250)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrecioBus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnNumeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            jt1.print(JTable.PrintMode.NORMAL);
        } catch (PrinterException ex) {
            Logger.getLogger(frmTablaEjemplo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed

        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            String conexion = "jdbc:odbc:venta";
            try {
                con= DriverManager.getConnection(conexion, "root","1234");
            } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}

            String consulta ="select VENTAID as CORRELATIVO,FECHADETALLE,CANTIDAD,PRECIO from detalleventa";
            //String consulta = "select CODPROVEEDOR as CODIGO,CODPRODUCTO,RUCPROVEEDOR as RUT_EMP,NOMBRE from Proveedor order by CODPROVEEDOR ";
            System.out.println(consulta);
            try{stmt=con.createStatement();
                rs=stmt.executeQuery(consulta);
            }catch (Exception e){System.out.println ("error en la consulta");}
            ResultSetMetaData rsm = rs.getMetaData();
            int cantidadColumnas = rsm.getColumnCount();
            for(int i =1;i<=cantidadColumnas;i++)
            { modelo.addColumn(rsm.getColumnLabel(i));}
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            rs.close();
        }catch (Exception ex){ex.printStackTrace();}

    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnPrecioBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecioBusActionPerformed
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            String conexion = "jdbc:odbc:venta";
            try {
                con= DriverManager.getConnection(conexion, "root","1234");
            } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
            try{
                int cod=Integer.parseInt(this.txtCodigo.getText());
                // String consulta = "select id,nombre,apellido,usuario,A,PRECIOUNITARIO,CANTIDAD from AUTOMOVIL ORDER BY MARCA";
                String consulta = "select VENTAID as CORRELATIVO,FECHADETALLE,CANTIDAD,PRECIO from detalleventa where precio="+cod;
                System.out.println(consulta);
                try{stmt=con.createStatement();
                    rs=stmt.executeQuery(consulta);
                }catch (Exception e){System.out.println ("error en la consulta");}
                ResultSetMetaData rsm = rs.getMetaData();
                int cantidadColumnas = rsm.getColumnCount();
                for(int i =1;i<=cantidadColumnas;i++)
                { modelo.addColumn(rsm.getColumnLabel(i));}
                while(rs.next()){
                    Object[] fila = new Object[cantidadColumnas];
                    for(int i = 0;i<cantidadColumnas;i++){
                        fila[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(fila);
                }
            }catch (Exception ex){JOptionPane.showMessageDialog(this, "SE esperaba Numero");}
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");

    }//GEN-LAST:event_btnPrecioBusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                  try{
DefaultTableModel modelo = new DefaultTableModel();
//this.jt1.setModel(vista);
this.jt1.setModel(modelo);


String conexion = "jdbc:odbc:venta";
        try {
     con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
      
   String cod=this.txtCodigo.getText();
  // String consulta = "select id,nombre,apellido,usuario,A,PRECIOUNITARIO,CANTIDAD from AUTOMOVIL ORDER BY MARCA";
 String consulta = "select VENTAID as CORRELATIVO,FECHADETALLE,CANTIDAD,PRECIO from detalleventa where FECHADETALLE="+cod;
  System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
    }catch (Exception e){System.out.println ("error en la consulta");}
    ResultSetMetaData rsm = rs.getMetaData();
    int cantidadColumnas = rsm.getColumnCount();
    for(int i =1;i<=cantidadColumnas;i++)
    { modelo.addColumn(rsm.getColumnLabel(i));}
    while(rs.next()){
    Object[] fila = new Object[cantidadColumnas];
    for(int i = 0;i<cantidadColumnas;i++){
    fila[i]=rs.getObject(i+1);
    }
    modelo.addRow(fila);
    }
 
}catch (Exception ex){ex.printStackTrace();}
 this.txtCodigo.setText("");
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        framePrincipal formInicial = new framePrincipal();
        formInicial.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        
     DefaultTableModel modelo = (DefaultTableModel) jt1.getModel();
        modelo.setRowCount(0);
        jt1.updateUI();

        this.txtCodigo.setText("");
        }
        public void mostrartable(String nombre){
            try{
                DefaultTableModel modelo = new DefaultTableModel();
                //this.jt1.setModel(vista);
                this.jt1.setModel(modelo);

                P.conectar();
                List tb = new ArrayList();
                List nom = new ArrayList();
                // String consulta = "select id,nombre,apellido,usuario,A,PRECIOUNITARIO,CANTIDAD from AUTOMOVIL ORDER BY MARCA";
                String consulta = "select ID,NOMBRE,APELLIDO,USUARIO from usuario where nombre='"+nombre+"'";
                //                   "SELECT id_t FROM empleados WHERE nombre = '"+nombre+"'";
                System.out.println(consulta);
                try{stmt=con.createStatement();
                    rs=stmt.executeQuery(consulta);
                }catch (Exception e){System.out.println ("error en la consulta");}
                ResultSetMetaData rsm = rs.getMetaData();
                int cantidadColumnas = rsm.getColumnCount();
                for(int i =1;i<=cantidadColumnas;i++)
                { modelo.addColumn(rsm.getColumnLabel(i));}
                while(rs.next()){
                    Object[] fila = new Object[cantidadColumnas];
                    for(int i = 0;i<cantidadColumnas;i++){
                        fila[i]=rs.getObject(i+1);
                        tb.add(jt1);

                    }
                    modelo.addRow(fila);
                }
                System.out.println(jt1);

                rs.close();
            }catch (Exception ex){ex.printStackTrace();}
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadActionPerformed
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            String conexion = "jdbc:odbc:venta";
            try {
                con= DriverManager.getConnection(conexion, "root","1234");
            } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
            try{
                int cod=Integer.parseInt(this.txtCodigo.getText());
                // String consulta = "select id,nombre,apellido,usuario,A,PRECIOUNITARIO,CANTIDAD from AUTOMOVIL ORDER BY MARCA";
                String consulta = "select VENTAID as CORRELATIVO,FECHADETALLE,CANTIDAD,PRECIO from detalleventa where CANTIDAD="+cod;
                System.out.println(consulta);
                try{stmt=con.createStatement();
                    rs=stmt.executeQuery(consulta);
                }catch (Exception e){System.out.println ("error en la consulta");}
                ResultSetMetaData rsm = rs.getMetaData();
                int cantidadColumnas = rsm.getColumnCount();
                for(int i =1;i<=cantidadColumnas;i++)
                { modelo.addColumn(rsm.getColumnLabel(i));}
                while(rs.next()){
                    Object[] fila = new Object[cantidadColumnas];
                    for(int i = 0;i<cantidadColumnas;i++){
                        fila[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(fila);
                }
            }catch (Exception ex){JOptionPane.showMessageDialog(this, "SE esperaba Numero");}
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");

    }//GEN-LAST:event_btnCantidadActionPerformed

    private void BtnNumeroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNumeroVentaActionPerformed
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            String conexion = "jdbc:odbc:venta";
            try {
                con= DriverManager.getConnection(conexion, "root","1234");
            } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
            try{
                int cod=Integer.parseInt(this.txtCodigo.getText());
                // String consulta = "select id,nombre,apellido,usuario,A,PRECIOUNITARIO,CANTIDAD from AUTOMOVIL ORDER BY MARCA";
                String consulta = "select VENTAID as CORRELATIVO,FECHADETALLE,CANTIDAD,PRECIO from detalleventa where ventaid="+cod;
                System.out.println(consulta);
                try{stmt=con.createStatement();
                    rs=stmt.executeQuery(consulta);
                }catch (Exception e){System.out.println ("error en la consulta");}
                ResultSetMetaData rsm = rs.getMetaData();
                int cantidadColumnas = rsm.getColumnCount();
                for(int i =1;i<=cantidadColumnas;i++)
                { modelo.addColumn(rsm.getColumnLabel(i));}
                while(rs.next()){
                    Object[] fila = new Object[cantidadColumnas];
                    for(int i = 0;i<cantidadColumnas;i++){
                        fila[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(fila);
                }
            }catch (Exception ex){JOptionPane.showMessageDialog(this, "SE esperaba Numero");}
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");

    }//GEN-LAST:event_BtnNumeroVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDetalleVentaBus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNumeroVenta;
    private javax.swing.JButton btnCantidad;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnPrecioBus;
    private javax.swing.JButton btnTodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
