/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.login;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author claudio
 */
public class frmEntrada extends javax.swing.JFrame {
//Controlador.login miEntrada = new Controlador.login();
    //usuario miUsuario = new usuario();
     private Connection con = null;
     private ResultSet rs = null;
     private Statement stmt= null;
     private String total;
    
    /**
     * Creates new form frmEntrada
     */
    public frmEntrada() {
       
        initComponents();
        setLocationRelativeTo(null);
        
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEntrar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUsuario1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.green);
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Pasword");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Desktop\\sistemaDeVentas2.0\\candadoNuevo.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingreso al Sistema");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("NEMESIS");

        btnEntrar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/Ok.png"))); // NOI18N
        btnEntrar1.setText("Entrar");
        btnEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseClicked(evt);
            }
        });
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/final.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuario");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        txtUsuario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario1.setForeground(java.awt.Color.blue);
        txtUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario1ActionPerformed(evt);
            }
        });
        txtUsuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuario1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntrar1)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseClicked
         
       conectar();
            
    String Usuario=this.txtUsuario1.getText();
    String Clave =this.txtPass.getText();
         
    //                                        from VENDEDOR where USUARIO ='"+codigo+"' and CONTRASENA = '"+contrasena+"'";
      String consulta = "select USUARIO,CLAVE from USuario where USUARIO='"+Usuario+"'and clave ='"+Clave+"'";
   
    System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
   
    }catch (Exception e){System.out.println ("error en la consulta:");}
              
    try{
      if (rs.next()){ 
          
            
            String Uss=rs.getString("USUARIO");
            String Pas=rs.getString("clave");
          
           framePrincipal Principal  = new framePrincipal();
        Principal.setVisible(true);
        this.dispose();
          
      }
      else{
      JOptionPane.showMessageDialog(this,"ERROR EN CONTRASEÑA,REGISTRO NO EXISTE EN BASE DE DATOS");
      }
    } catch (Exception e) {
           System.out.println("error en Datos");
       }
    
       this.txtPass.setText("");
       this.txtUsuario1.setText("");
       
         
       
    }//GEN-LAST:event_btnEntrar1MouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
          addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    public void conectar(){

 String conexion = "jdbc:odbc:venta";
        try {
     con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}

}
    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        
       conectar();
            
    String Usuario=this.txtUsuario1.getText();
    String Clave =this.txtPass.getText();
         
    //                                        from VENDEDOR where USUARIO ='"+codigo+"' and CONTRASENA = '"+contrasena+"'";
      String consulta = "select USUARIO,CLAVE from USuario where USUARIO='"+Usuario+"'and clave ='"+Clave+"'";
   
    System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
   
    }catch (Exception e){System.out.println ("error en la consulta:");}
              
    try{
      if (rs.next()){ 
          
            
            String Uss=rs.getString("USUARIO");
            String Pas=rs.getString("clave");
          
           framePrincipal Principal  = new framePrincipal();
        Principal.setVisible(true);
        this.dispose();
          
      }
      else{
      JOptionPane.showMessageDialog(this,"ERROR EN CONTRASEÑA,REGISTRO NO EXISTE EN BASE DE DATOS");
      }
    } catch (Exception e) {
           System.out.println("error en Datos");
       }
    
       this.txtPass.setText("");
       this.txtUsuario1.setText("");
       
         
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario1ActionPerformed
        // TODO add your handling code here:
          
       conectar();
            
    String Usuario=this.txtUsuario1.getText();
    String Clave =this.txtPass.getText();
         
    //                                        from VENDEDOR where USUARIO ='"+codigo+"' and CONTRASENA = '"+contrasena+"'";
      String consulta = "select USUARIO,CLAVE from USuario where USUARIO='"+Usuario+"'and clave ='"+Clave+"'";
   
    System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
   
    }catch (Exception e){System.out.println ("error en la consulta:");}
              
    try{
      if (rs.next()){ 
          
            
            String Uss=rs.getString("USUARIO");
            String Pas=rs.getString("clave");
          
           framePrincipal Principal  = new framePrincipal();
        Principal.setVisible(true);
        this.dispose();
          
      }
      else{
      JOptionPane.showMessageDialog(this,"ERROR EN CONTRASEÑA,REGISTRO NO EXISTE EN BASE DE DATOS");
      }
    } catch (Exception e) {
           System.out.println("error en Datos");
       }
    
       this.txtPass.setText("");
       this.txtUsuario1.setText("");
       
         
       
    }//GEN-LAST:event_txtUsuario1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    // frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
     // frame.setVisible(true);
         
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
          addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
          addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_formWindowClosed

    private void txtUsuario1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuario1KeyTyped
        
         if(txtUsuario1.getText().length() >= 10){
evt.consume();
}
        
    }//GEN-LAST:event_txtUsuario1KeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        // TODO add your handling code here:
        if(txtPass.getText().length() >= 10){
evt.consume();
}
    }//GEN-LAST:event_txtPassKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEntrada().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
