/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author claudio
 */
public class frmIngresoRestringido extends javax.swing.JFrame {
     private Connection con = null;
     private ResultSet rs = null;
     private Statement stmt= null;
    /**
     * Creates new form frmIngresoRestringido
     */
    public frmIngresoRestringido() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngreso = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblRestriccion = new javax.swing.JLabel();
        lblPaswork = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEntrar1 = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUsuario1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblIngreso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblIngreso.setForeground(java.awt.Color.blue);
        lblIngreso.setText("INGRESO A MANTENEDORES");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/atras3.png"))); // NOI18N
        jButton4.setText("Volver");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblRestriccion.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Desktop\\sistemaDeVentas2.0\\privado.png")); // NOI18N

        lblPaswork.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPaswork.setText("Pasword");

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/final.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEntrar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/Ok.png"))); // NOI18N
        btnEntrar1.setText("Entrar");
        btnEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseClicked(evt);
            }
        });
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setText("Usuario");

        txtPass.setForeground(java.awt.Color.blue);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        txtUsuario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario1.setForeground(java.awt.Color.blue);
        txtUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPaswork)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnEntrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRestriccion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblRestriccion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaswork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrar1))
                .addGap(9, 9, 9)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        framePrincipal formInicial = new framePrincipal();
        formInicial.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnEntrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseClicked
                                                
        
       conectar();
            
    String Usuario=this.txtUsuario1.getText();
    String Clave =this.txtPass.getText();
         
    //                                        from VENDEDOR where USUARIO ='"+codigo+"' and CONTRASENA = '"+contrasena+"'";
      String consulta = "select USUARIO,CLAVE from USuario where USUARIO='"+Usuario+"'and clave ='"+Clave+"'";
   
    System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
   
    }catch (Exception e){System.out.println ("error en la consulta:");}
              
    try{
      if (rs.next()){ 
          
            
            String Uss=rs.getString("USUARIO");
            String Pas=rs.getString("clave");
          
           frmMantenimiento mantenimiento  = new frmMantenimiento();
        mantenimiento.setVisible(true);
        this.dispose();
          
      }
      else{
      JOptionPane.showMessageDialog(this,"ERROR EN CONTRASEÑA,REGISTRO NO EXISTE EN BASE DE DATOS");
      }
    } catch (Exception e) {
           System.out.println("error en Datos");
       }
    
       this.txtPass.setText("");
       this.txtUsuario1.setText("");
       
         
      
    }//GEN-LAST:event_btnEntrar1MouseClicked

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
                                               
        
       conectar();
            
    String Usuario=this.txtUsuario1.getText();
    String Clave =this.txtPass.getText();
         
    //                                        from VENDEDOR where USUARIO ='"+codigo+"' and CONTRASENA = '"+contrasena+"'";
      String consulta = "select USUARIO,CLAVE from USuario where USUARIO='"+Usuario+"'and clave ='"+Clave+"'";
   
    System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
   
    }catch (Exception e){System.out.println ("error en la consulta:");}
              
    try{
      if (rs.next()){ 
          
            
            String Uss=rs.getString("USUARIO");
            String Pas=rs.getString("clave");
          
           frmMantenimiento mantenimiento  = new frmMantenimiento();
        mantenimiento.setVisible(true);
        this.dispose();
          
      }
      else{
      JOptionPane.showMessageDialog(this,"ERROR EN CONTRASEÑA,REGISTRO NO EXISTE EN BASE DE DATOS");
      }
    } catch (Exception e) {
           System.out.println("error en Datos");
       }
    
       this.txtPass.setText("");
       this.txtUsuario1.setText("");
       
         
    }//GEN-LAST:event_txtPassActionPerformed
 public void conectar(){

 String conexion = "jdbc:odbc:venta";
        try {
     con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}

}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
         
        
        
    }//GEN-LAST:event_formWindowOpened

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassMouseClicked

    private void txtUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario1ActionPerformed
                                                  
        
       conectar();
            
    String Usuario=this.txtUsuario1.getText();
    String Clave =this.txtPass.getText();
         
    //                                        from VENDEDOR where USUARIO ='"+codigo+"' and CONTRASENA = '"+contrasena+"'";
      String consulta = "select USUARIO,CLAVE from USuario where USUARIO='"+Usuario+"'and clave ='"+Clave+"'";
   
    System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
   
    }catch (Exception e){System.out.println ("error en la consulta:");}
              
    try{
      if (rs.next()){ 
          
            
            String Uss=rs.getString("USUARIO");
            String Pas=rs.getString("clave");
          
           frmMantenimiento mantenimiento  = new frmMantenimiento();
        mantenimiento.setVisible(true);
        this.dispose();
          
      }
      else{
      JOptionPane.showMessageDialog(this,"ERROR EN CONTRASEÑA,REGISTRO NO EXISTE EN BASE DE DATOS");
      }
    } catch (Exception e) {
           System.out.println("error en Datos");
       }
    
       this.txtPass.setText("");
       this.txtUsuario1.setText("");
       
         
    
    
     
    }//GEN-LAST:event_txtUsuario1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
          addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngresoRestringido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngresoRestringido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngresoRestringido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngresoRestringido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngresoRestringido().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblPaswork;
    private javax.swing.JLabel lblRestriccion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
