/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import Controlador.producto;
import Controlador.usuario;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author claudio
 */
public class frmProducto extends javax.swing.JFrame {
   
 producto miProducto = new producto();
 private ResultSetMetaData  rsm = null;
  private Connection con = null;
  private ResultSet rs = null;
  private Statement stmt= null;
  public String codigoMaestro=null;
 // private ResultSetMetaData  rsm = null;
  


    /**
     * Creates new form frmProducto
     */
    public frmProducto() {
        initComponents();
        setLocationRelativeTo(null);
        String fecha;
  Date fecha1 = new Date ();
  fecha = fecha1.toLocaleString();
  System.out.println(fecha);
  this.txtfechaactualizacion.setText(fecha);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAñadir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcodproducto = new javax.swing.JTextField();
        txtserieProducto1 = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        txtStockActual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpreciocosto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprecioventa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfechaactualizacion = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        txtidProveedor = new javax.swing.JTextField();
        btnMostrarTabla = new javax.swing.JButton();
        txtSuma = new javax.swing.JTextField();
        txtCodigoBarra = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnEliminaFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAñadir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/add.png"))); // NOI18N
        btnAñadir.setText("AÑADIR");
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/lupa.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/actualizar.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANTENEDOR DE PRODUCTOS");

        txtcodproducto.setEditable(false);

        txtserieProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtserieProducto1MouseClicked(evt);
            }
        });
        txtserieProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserieProducto1ActionPerformed(evt);
            }
        });
        txtserieProducto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtserieProducto1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtserieProducto1KeyTyped(evt);
            }
        });

        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });

        txttipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttipoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("SERIE PRODUCTO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("MARCA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("TIPO");

        jt1.setForeground(java.awt.Color.blue);
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jt1);

        jButton5.setText("VOLVER");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        txtStockActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockActualKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("STOCK ACTUAL");

        txtpreciocosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpreciocostoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("PRECIO COSTO");

        txtprecioventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioventaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PRECIO VENTA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("FECHA ");

        txtfechaactualizacion.setEditable(false);
        txtfechaactualizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechaactualizacionKeyTyped(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label.setText("ID PROVEEDOR");

        txtidProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidProveedorActionPerformed(evt);
            }
        });
        txtidProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidProveedorKeyTyped(evt);
            }
        });

        btnMostrarTabla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/mostrar.png"))); // NOI18N
        btnMostrarTabla.setText("Mostrar ");
        btnMostrarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTablaMouseClicked(evt);
            }
        });
        btnMostrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTablaActionPerformed(evt);
            }
        });

        txtSuma.setEditable(false);

        txtCodigoBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoBarraMouseClicked(evt);
            }
        });
        txtCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarraActionPerformed(evt);
            }
        });
        txtCodigoBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBarraKeyTyped(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/limpiar.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/print.png"))); // NOI18N
        jButton1.setText("Print  Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEliminaFila.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminaFila.setText("ELIMINA FILA");
        btnEliminaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label)
                                        .addGap(17, 17, 17)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpreciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcodproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtserieProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoBarra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMostrarTabla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtfechaactualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfechaactualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addComponent(txtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(btnEliminaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcodproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtserieProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtpreciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label)
                            .addComponent(txtidProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        framePrincipal  frame = new framePrincipal();
        frame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
     if(this.txtserieProducto1.getText().equals("")||this.txtpreciocosto.getText().equals("")||this.txtprecioventa.getText().equals("")||this.txtidProveedor.getText().equals("")){
         System.out.println("DEBE INGRESAR PARAMETROS CODIGO DE BARRA,PRECIOCOSTO");
         JOptionPane.showMessageDialog(this, "DEBE INGRESAR PARAMETROS CODIGO DE BARRA,PRECIOCOSTO");
     }
     else{
       
        boolean exito = true;
        //transformando los getext a enteros
        
         try{  // codigo       =     Integer.parseInt(this.txtcodproducto.getText());
         int   preciocosto  =     Integer.parseInt(txtpreciocosto.getText());
         int   precioventa  =     Integer.parseInt(txtprecioventa.getText());
         int   idproveedor  =     Integer.parseInt(txtidProveedor.getText());
         int   stock        =     Integer.parseInt(this.txtStockActual.getText());
        
          
         miProducto.setSerieProducto(this.txtserieProducto1.getText());
         miProducto.setMarca(this.txtmarca.getText());
         miProducto.setTipo(this.txttipo.getText());
         miProducto.setPreciocosto(preciocosto);
         miProducto.setPrecioventa(precioventa);
         miProducto.setStockActual(stock);
         miProducto.setFechaactualizacion(this.txtfechaactualizacion.getText());
         miProducto.setIdProveedor(idproveedor);
         
         int suma =precioventa-preciocosto;
         String valorTotal = Double.toString(suma);
         txtSuma.setText(valorTotal);
          }catch(Exception e){ 
             System.out.println("debes ingresar numeros no letras");}
       if (miProducto.insertar()){
         //   JOptionPane.showMessageDialog(null,"Se inserto correctamente la Producto");
             this.txtcodproducto.setText("");
             this.txtcodproducto.setText("");
             this.txtserieProducto1.setText("");
             this.txtmarca.setText("");
             this.txttipo.setText("");
             this.txtStockActual.setText("");
           
             this.txtpreciocosto.setText("");
             this.txtprecioventa.setText("");
             this.txtfechaactualizacion.setText("");
             this.txtidProveedor.setText("");
             
             
  /*           this.txtidProveedor.setText("");
  }
        else JOptionPane.showMessageDialog(null,"No se pudo insertar nuevo producto");
 }
        else JOptionPane.showMessageDialog(null,"No se puedo insertar por problemas de validacion");
        */
    }//GEN-LAST:event_btnAñadirMouseClicked
   }  
    }
    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
if(this.txtCodigoBarra.getText().equals("")){
    System.out.println("DEBES INGRESAR EL CODIGO A BUSCAR");
    JOptionPane.showMessageDialog(this, "DEBES INGRESAR EL CODIGO A BUSCAR");
}else{
    //limpio todos los jtextfields existitos
        this.txtcodproducto.setText("");
        this.txtserieProducto1.setText("");
        this.txtmarca.setText("");
        this.txttipo.setText("");
      
        this.txtpreciocosto.setText("");
        this.txtprecioventa.setText("");
        this.txtfechaactualizacion.setText("");
        this.txtidProveedor.setText("");
        
 String codigoBarra =this.txtCodigoBarra.getText();
    miProducto.Buscar(codigoBarra);
    try {
        miProducto.consultarStock(codigoBarra);
    } catch (SQLException ex) {
        Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
    }
     this.txtCodigoBarra.setText(miProducto.getSerieProducto());
     this.txtcodproducto.setText(""+miProducto.getCodproducto());
     this.txtserieProducto1.setText(""+miProducto.getSerieProducto());
     this.txtmarca.setText(miProducto.getMarca());
     this.txttipo.setText(miProducto.getTipo());
    
     this.txtStockActual.setText(""+miProducto.resultado);
     this.txtpreciocosto.setText(""+miProducto.getPreciocosto());
     this.txtprecioventa.setText(""+miProducto.getPrecioventa());
     this.txtfechaactualizacion.setText(miProducto.getFechaactualizacion());
     this.txtidProveedor.setText(""+miProducto.getIdProveedor());
     
      
        
}   
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnMostrarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTablaMouseClicked
        // TODO add your handling code here:
           // TODO add your handling code here:
        try{
DefaultTableModel modelo = new DefaultTableModel();
//this.jt1.setModel(vista);
this.jt1.setModel(modelo);


String conexion = "jdbc:odbc:venta";
        try {
     con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}


      String consulta = "select CODPRODUCTO AS CODIGO,serieproducto as SERIE,MARCA,TIPO,StockActual AS STOCK,PRECIOCOSTO AS PRECIO_E,FECHAACTUALIZACION AS FECHA from PRODUCTO ORDER BY CODPRODUCTO  ";
      //                "select ID,NOMBRE,APELLIDO,USUARIO from usuario where nombre=  '"+nombre+"'";
  System.out.println(consulta);
    try{stmt=con.createStatement();
    rs=stmt.executeQuery(consulta);
    }catch (Exception e){System.out.println ("error en la consulta");}
    ResultSetMetaData rsm = rs.getMetaData();
    int cantidadColumnas = rsm.getColumnCount();
    for(int i =1;i<=cantidadColumnas;i++)
    { modelo.addColumn(rsm.getColumnLabel(i));}
    while(rs.next()){
    Object[] fila = new Object[cantidadColumnas];
    for(int i = 0;i<cantidadColumnas;i++){
    fila[i]=rs.getObject(i+1);
    }
    modelo.addRow(fila);
    }
 rs.close();
}catch (Exception ex){ex.printStackTrace();}
    }//GEN-LAST:event_btnMostrarTablaMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handlinis
        this.txtcodproducto.setText("");
        this.txtCodigoBarra.setText("");
        this.txtserieProducto1.setText("");
        this.txtcodproducto.setText("");
        this.txtmarca.setText("");
        this.txttipo.setText("");
     
        this.txtStockActual.setText("");
        this.txtpreciocosto.setText("");
        this.txtprecioventa.setText("");
        this.txtfechaactualizacion.setText("");
        this.txtidProveedor.setText("");
        System.out.println("JTEXTFIELDS LIMPIADOS EXITOSAMENTE");
        
     DefaultTableModel modelo = (DefaultTableModel) jt1.getModel();
        modelo.setRowCount(0);
        jt1.updateUI();
        
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void txtCodigoBarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoBarraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarraMouseClicked

    private void txtCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarraActionPerformed
        // TODO add your handling code here:
        if(this.txtCodigoBarra.getText().equals("")){
    System.out.println("DEBES INGRESAR EL CODIGO A BUSCAR");
    JOptionPane.showMessageDialog(this, "DEBES INGRESAR EL CODIGO A BUSCAR");
}else{
    //limpio todos los jtextfields existitos
        this.txtcodproducto.setText("");
        this.txtserieProducto1.setText("");
        this.txtmarca.setText("");
        this.txttipo.setText("");
     
        this.txtpreciocosto.setText("");
        this.txtprecioventa.setText("");
        this.txtfechaactualizacion.setText("");
        this.txtidProveedor.setText("");
        
 String codigoBarra =this.txtCodigoBarra.getText();
    miProducto.Buscar(codigoBarra);
     
    try {
        miProducto.consultarStock(codigoBarra);
       
    } catch (SQLException ex) {
        Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
    }
     this.txtCodigoBarra.setText(miProducto.getSerieProducto());
     this.txtcodproducto.setText(""+miProducto.getCodproducto());
     this.txtserieProducto1.setText(""+miProducto.getSerieProducto());
     this.txtmarca.setText(miProducto.getMarca());
     this.txttipo.setText(miProducto.getTipo());
   
     this.txtStockActual.setText(""+miProducto.getStockActual());
     this.txtpreciocosto.setText(""+miProducto.getPreciocosto());
     this.txtprecioventa.setText(""+miProducto.getPrecioventa());
     this.txtfechaactualizacion.setText(miProducto.getFechaactualizacion());
     this.txtidProveedor.setText(""+miProducto.getIdProveedor());
     
      
        
}   
    }//GEN-LAST:event_txtCodigoBarraActionPerformed

    private void txtserieProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserieProducto1ActionPerformed
// TODO add your handling code here:
        this.txtserieProducto1.requestFocus();
       this.txtmarca.requestFocus();
        
                //textField.requestFocusInWindow();﻿
           String conexion="jdbc:odbc:venta";
   try { con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}  
        try {
           //miProducto.conectar();
            String codigo = null;
            //codigo = JOptionPane.showInputDialog("Ingrese el codigo a Buscar: ");
           codigo=txtserieProducto1.getText();
            String consulta=("select SERIEPRODUCTO  from producto where SERIEPRODUCTO='"+codigo+"'");
           // String consulta="select serieproducto from producto";
          //   System.out.println(consulta);
        stmt = con.createStatement();
        rs = stmt.executeQuery(consulta);
        
        String codigo2=null;
          if(rs.next()){
                     String mensaje1="Codigo Existente";
                  System.out.println(mensaje1);
                  JOptionPane.showMessageDialog(this,mensaje1);
                  int ax = JOptionPane.showConfirmDialog(null, "DESEA MODIFICAR EL REGISTRO");
        if(ax == JOptionPane.YES_OPTION){
           
             miProducto.Buscar(codigo);
             
            // de aqui
                          int axx = JOptionPane.showConfirmDialog(null, "AUMENTAR STOCK DEL PRODUCTO?");
        if(axx == JOptionPane.YES_OPTION){
            int valor=1;
          valor=miProducto.stockPublico++;
          System.out.println(valor);
         
          
            
            
        }
        else if(axx == JOptionPane.NO_OPTION){
            
          
           
            
     
      
       
                   
        }
            //hasta aca
             {
    //limpio todos los jtextfields existitos
        this.txtcodproducto.setText("");
        this.txtserieProducto1.setText("");
        this.txtmarca.setText("");
        this.txttipo.setText("");
     
        this.txtpreciocosto.setText("");
        this.txtprecioventa.setText("");
        this.txtfechaactualizacion.setText("");
        this.txtidProveedor.setText("");
        
// String codigoBarra =this.txtSerieProducto1.getText();
   String codigoBarra=this.txtserieProducto1.getText();
        miProducto.Buscar(codigo);
     
    try {
        miProducto.consultarStock(codigo);
       
    } catch (SQLException ex) {
        Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
    }
    // this.txtSerieProducto1.setText(miProducto.getSerieProducto());
  //77 this.txtserieProducto1.setText(miProducto.getSerieProducto());
     this.txtcodproducto.setText(""+miProducto.getCodproducto());
     this.txtserieProducto1.setText(""+miProducto.getSerieProducto());
     this.txtmarca.setText(miProducto.getMarca());
     this.txttipo.setText(miProducto.getTipo());
    
     this.txtStockActual.setText(""+miProducto.resultado);
     this.txtpreciocosto.setText(""+miProducto.getPreciocosto());
     this.txtprecioventa.setText(""+miProducto.getPrecioventa());
     this.txtfechaactualizacion.setText(miProducto.getFechaactualizacion());
     this.txtidProveedor.setText(""+miProducto.getIdProveedor());
     
      
        
}   
//---------------------------------------------------------------------
             
            
            
           
        }
        else if(ax == JOptionPane.NO_OPTION){
            //JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
            this.txtserieProducto1.setText("");
        }
        }else{
                     String mensaje2="Codigo no Existente";
                   System.out.println(mensaje2);
                    JOptionPane.showMessageDialog(this,mensaje2);
                    int ax = JOptionPane.showConfirmDialog(null, "Deseas Agregar Registro");
        if(ax == JOptionPane.YES_OPTION){
          //aqui 
            if(     this.txtserieProducto1.getText().equals("")||
                    this.txtmarca.getText().equals("")||
                    this.txtpreciocosto.getText().equals("")||
                    this.txtpreciocosto.getText().equals("")||
                    this.txtpreciocosto.getText().equals("")||
                    this.txtprecioventa.getText().equals("")||
                    this.txtidProveedor.getText().equals("")){
            } // JOptionPane.showMessageDialog(this,"debes llenar textfields necesarios para la insercion");}
            else{
             JOptionPane.showMessageDialog(this,"ingresado");
              miProducto.insertar();
              JOptionPane.showMessageDialog(null, "registro agregado exitosamente");
            }
            
            
        }
        else if(ax == JOptionPane.NO_OPTION){
            //JOptionPane.showMessageDialog(null, "Cerrar");
            
       
        System.out.println("JTEXTFIELDS LIMPIADOS EXITOSAMENTE");
        
                this.txtserieProducto1.setText("");
       
                   
        }
                    
                   
                    }
            
            
           
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

                    
       
    }//GEN-LAST:event_txtserieProducto1ActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
       if(this.txtcodproducto.getText().equals("")|| this.txtidProveedor.getText().equals("")
                ||this.txtserieProducto1.getText().equals("")||this.txtpreciocosto.getText().equals("")
               ||this.txtprecioventa.getText().equals("")){
            String mensaje="INGRESE PARAMETROS";
        System.out.println(mensaje);
        JOptionPane.showMessageDialog(this, mensaje);
        }
        else{
        JOptionPane.showMessageDialog(null,"Registro Actualizado Correctamente");
        
       
      //  miProveedor.setCodproducto(Integer.parseInt(this.txtCODPRODUCTO.getText()));
       // miProducto.setCodproducto(Integer.parseInt(this.txtcodproducto.getText()));
        int codProducto=Integer.parseInt(this.txtcodproducto.getText());
        miProducto.setSerieProducto(this.txtserieProducto1.getText());
        miProducto.setMarca(this.txtmarca.getText());
        miProducto.setTipo(this.txttipo.getText());
        miProducto.setStockActual(Integer.parseInt(this.txtStockActual.getText()));
        miProducto.setPreciocosto(Integer.parseInt(this.txtpreciocosto.getText()));
        miProducto.setPrecioventa(Integer.parseInt(this.txtprecioventa.getText()));
        miProducto.setIdProveedor(Integer.parseInt(this.txtidProveedor.getText()));
        miProducto.setFechaactualizacion(this.txtfechaactualizacion.getText());
       
        miProducto.actualizarProducto(codProducto);
        
        
        }  
    }//GEN-LAST:event_btnActualizarMouseClicked
 private void limpiar(){
        this.txtcodproducto.setText("");
        this.txtserieProducto1.setText("");
        this.txtmarca.setText("");
        this.txttipo.setText("");
        this.txtStockActual.setText("");
        this.txtpreciocosto.setText("");
        this.txtprecioventa.setText("");
        this.txtfechaactualizacion.setText("");
        this.txtidProveedor.setText("");
      
 }
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        limpiar();
        miProducto.eliminar();
       
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //actualizar algun dato modificado 
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtpreciocostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreciocostoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
        
    }//GEN-LAST:event_txtpreciocostoKeyTyped

    private void txtprecioventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioventaKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
    }//GEN-LAST:event_txtprecioventaKeyTyped

    private void txtidProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidProveedorKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
    }//GEN-LAST:event_txtidProveedorKeyTyped

    private void txtserieProducto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserieProducto1KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
    }//GEN-LAST:event_txtserieProducto1KeyTyped

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void txttipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttipoKeyTyped
      
    }//GEN-LAST:event_txttipoKeyTyped

    private void txtfechaactualizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechaactualizacionKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
    }//GEN-LAST:event_txtfechaactualizacionKeyTyped

    private void txtCodigoBarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarraKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
    }//GEN-LAST:event_txtCodigoBarraKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       this.txtserieProducto1.requestFocusInWindow();
      
    }//GEN-LAST:event_formWindowOpened

    private void txtserieProducto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserieProducto1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserieProducto1KeyPressed

    private void txtserieProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtserieProducto1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserieProducto1MouseClicked

    private void txtidProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidProveedorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnMostrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarTablaActionPerformed

    private void txtStockActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockActualKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
         if(txtStockActual.getText().length() >= 10){
evt.consume();
}
    }//GEN-LAST:event_txtStockActualKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
          jt1.print(JTable.PrintMode.NORMAL);
      } catch (PrinterException ex) {
          Logger.getLogger(frmTablaEjemplo.class.getName()).log(Level.SEVERE, null, ex);
      }       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaFilaActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel tabla = new DefaultTableModel();
        int fila = 0,n;
        this.jt1.getSelectedRow();
        if(fila>=0){
        tabla.removeRow(fila);
        }   
        else{
        JOptionPane.showMessageDialog(null, "NO SELECCIONO");
        }
        }catch(Exception e) { }
    }//GEN-LAST:event_btnEliminaFilaActionPerformed

    private void jt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jt1KeyTyped
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>a

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProducto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminaFila;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtSuma;
    private javax.swing.JTextField txtcodproducto;
    private javax.swing.JTextField txtfechaactualizacion;
    private javax.swing.JTextField txtidProveedor;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtpreciocosto;
    private javax.swing.JTextField txtprecioventa;
    private javax.swing.JTextField txtserieProducto1;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
