/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author claudio
 */
public class frmVentasBus extends javax.swing.JFrame {
  private Connection con = null;
  private ResultSet rs = null;
  private Statement stmt= null;
  private ResultSetMetaData  rsm = null;
    /**
     * Creates new form frmVentasBus
     */
    public frmVentasBus() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jCalendarDemo1 = new com.toedter.calendar.JCalendarDemo();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btnMostrarTodo = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        btnCodigoInterno = new javax.swing.JButton();
        btnSerieProducto = new javax.swing.JButton();
        btnBusquedaPorClienteVenta = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        btnMedioDePago = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jCalendarDemo1Layout = new javax.swing.GroupLayout(jCalendarDemo1.getContentPane());
        jCalendarDemo1.getContentPane().setLayout(jCalendarDemo1Layout);
        jCalendarDemo1Layout.setHorizontalGroup(
            jCalendarDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jCalendarDemo1Layout.setVerticalGroup(
            jCalendarDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("BUSQUEDA DE VENTAS");

        jt1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jt1.setForeground(java.awt.Color.blue);
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt1);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/atras3.png"))); // NOI18N
        jButton4.setText("Volver");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnMostrarTodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMostrarTodo.setText("TOTAL");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        btnMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMarca.setText("LIMPIAR");
        btnMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarcaMouseClicked(evt);
            }
        });
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        btnCodigoInterno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCodigoInterno.setText("N° VENTA");
        btnCodigoInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoInternoActionPerformed(evt);
            }
        });

        btnSerieProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSerieProducto.setText("FECHAS");

        btnBusquedaPorClienteVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBusquedaPorClienteVenta.setText("CLIENTE");
        btnBusquedaPorClienteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaPorClienteVentaActionPerformed(evt);
            }
        });

        btnVendedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVendedor.setText("VENDEDOR");
        btnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorActionPerformed(evt);
            }
        });

        btnMedioDePago.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMedioDePago.setText("MEDIO PAGO");
        btnMedioDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioDePagoActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("PRINT TABLE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Ingrese parametros de Busqueda");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Detalles de Consulta Actual");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Desde ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Hasta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCodigo)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnCodigoInterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnMedioDePago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnBusquedaPorClienteVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(11, 11, 11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnMostrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(btnSerieProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCodigoInterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSerieProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btnBusquedaPorClienteVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(btnMedioDePago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        framePrincipal formInicial = new framePrincipal();
        formInicial.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked
 public boolean conectar() {
      
 
         String conexion = "jdbc:odbc:venta";
     try {
     con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
       
            
        return true;
   }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            conectar();
            String consulta = "select idVenta as  NRo_Venta,IDCLIENTE  as CLIENTE,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta ORDER BY NRo_Venta ";
            //                "select idVenta as ID,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta ORDER BY ID ";
            System.out.println(consulta);
            try{stmt=con.createStatement();
                rs=stmt.executeQuery(consulta);
            }catch (Exception e){System.out.println ("error en la consulta");}
            ResultSetMetaData rsm = rs.getMetaData();
            int cantidadColumnas = rsm.getColumnCount();
            for(int i =1;i<=cantidadColumnas;i++)
            { modelo.addColumn(rsm.getColumnLabel(i));}
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            rs.close();
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            conectar();
            if(this.txtCodigo.getText().equals("")){
                JOptionPane.showMessageDialog(this, "INGRESE MARCA A PROCESAR");
            }
            String Marca =this.txtCodigo.getText();
            String consulta = "select CODPRODUCTO AS CODIGO,serieproducto as SERIE,MARCA,TIPO,StockActual AS STOCK from PRODUCTO where MARCA='"+Marca+"'";
            //                "select ID,NOMBRE,APELLIDO,USUARIO from usuario where nombre=  '"+nombre+"'";
            System.out.println(consulta);
            try{stmt=con.createStatement();
                rs=stmt.executeQuery(consulta);
            }catch (Exception e){System.out.println ("error en la consulta");}
            ResultSetMetaData rsm = rs.getMetaData();
            int cantidadColumnas = rsm.getColumnCount();
            for(int i =1;i<=cantidadColumnas;i++)
            { modelo.addColumn(rsm.getColumnLabel(i));}
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }

        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");
        }
        public void mostrartable(String nombre){
            try{
                DefaultTableModel modelo = new DefaultTableModel();
                //this.jt1.setModel(vista);
                this.jt1.setModel(modelo);

                conectar();
                List tb = new ArrayList();
                List nom = new ArrayList();
                // String consulta = "select id,nombre,apellido,usuario,A,PRECIOUNITARIO,CANTIDAD from AUTOMOVIL ORDER BY MARCA";
                String consulta = "select ID,NOMBRE,APELLIDO,USUARIO from usuario where nombre='"+nombre+"'";
                //                   "SELECT id_t FROM empleados WHERE nombre = '"+nombre+"'";
                System.out.println(consulta);
                try{stmt=con.createStatement();
                    rs=stmt.executeQuery(consulta);
                }catch (Exception e){System.out.println ("error en la consulta");}
                ResultSetMetaData rsm = rs.getMetaData();
                int cantidadColumnas = rsm.getColumnCount();
                for(int i =1;i<=cantidadColumnas;i++)
                { modelo.addColumn(rsm.getColumnLabel(i));}
                while(rs.next()){
                    Object[] fila = new Object[cantidadColumnas];
                    for(int i = 0;i<cantidadColumnas;i++){
                        fila[i]=rs.getObject(i+1);
                        tb.add(jt1);

                    }
                    modelo.addRow(fila);
                }
                System.out.println(jt1);

                rs.close();
            }catch (Exception ex){ex.printStackTrace();}

    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnCodigoInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoInternoActionPerformed

        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            conectar();
            
            if(this.txtCodigo.getText().equals("")){
                JOptionPane.showMessageDialog(this, "INGRESE CODIGO A CONSULTAR");
            }
            else{
               
                 try{   
                int  cod =Integer.parseInt(this.txtCodigo.getText());
                 
                 
               
                
                String consulta = "select idVenta as  NRo_Venta,IDCLIENTE  as CLIENTE,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta where idventa= "+cod;
              
                System.out.println(consulta);
                try{stmt=con.createStatement();
                    rs=stmt.executeQuery(consulta);
                }catch (Exception e){System.out.println ("error en la consulta");}
                ResultSetMetaData rsm = rs.getMetaData();
                int cantidadColumnas = rsm.getColumnCount();
                
                for(int i =1;i<=cantidadColumnas;i++)
                { modelo.addColumn(rsm.getColumnLabel(i));}
                while(rs.next()){
                    Object[] fila = new Object[cantidadColumnas];
                    for(int i = 0;i<cantidadColumnas;i++){
                        fila[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(fila);
                }

                
}catch(Exception e){
                 JOptionPane.showMessageDialog(this,"SE ESPERO DATO ENTERO O NUMERICO");
                         }
            }
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");
    }//GEN-LAST:event_btnCodigoInternoActionPerformed

    private void btnBusquedaPorClienteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaPorClienteVentaActionPerformed
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            conectar();
            try{
            int codCliente=Integer.parseInt(this.txtCodigo.getText());
            
            String consulta = "select idVenta as  NRo_Venta,IDCLIENTE  as CLIENTE,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta where idCliente="+codCliente;
            //                "select idVenta as ID,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta ORDER BY ID ";
            System.out.println(consulta);
            try{stmt=con.createStatement();
                rs=stmt.executeQuery(consulta);
            }catch (Exception e){System.out.println ("error en la consulta");}
            ResultSetMetaData rsm = rs.getMetaData();
            int cantidadColumnas = rsm.getColumnCount();
            for(int i =1;i<=cantidadColumnas;i++)
            { modelo.addColumn(rsm.getColumnLabel(i));}
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            }catch(Exception e){
                 JOptionPane.showMessageDialog(this,"SE ESPERO DATO NUMERICO ASOCIADO A ID DEL CLIENTE");
                         }
           
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");
                        
    }//GEN-LAST:event_btnBusquedaPorClienteVentaActionPerformed

    private void btnMedioDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioDePagoActionPerformed
     try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            conectar();
            try{
            String medioPago=this.txtCodigo.getText();
            
            String consulta = "select idVenta as  NRo_Venta,IDCLIENTE  as CLIENTE,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta where Mediodepago='"+medioPago+"'";
            //                "select idVenta as ID,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta ORDER BY ID ";
            System.out.println(consulta);
            try{stmt=con.createStatement();
                rs=stmt.executeQuery(consulta);
            }catch (Exception e){System.out.println ("error en la consulta");}
            ResultSetMetaData rsm = rs.getMetaData();
            int cantidadColumnas = rsm.getColumnCount();
            for(int i =1;i<=cantidadColumnas;i++)
            { modelo.addColumn(rsm.getColumnLabel(i));}
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }}
            catch(Exception e){
            JOptionPane.showMessageDialog(this,"SE ESPERABA TIPO DE MEDIO DE PAGO...EFECTICO,DEBITO,CHEQUE");
            }
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");
                        
             
    }//GEN-LAST:event_btnMedioDePagoActionPerformed

    private void btnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            //this.jt1.setModel(vista);
            this.jt1.setModel(modelo);

            conectar();
           
            String vendedor=this.txtCodigo.getText();
            String consulta = "select idVenta as  NRo_Venta,IDCLIENTE  as CLIENTE,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta where vendedor='"+vendedor+"'";
            //                "select idVenta as ID,fechaventa as Fecha,vendedor as Vendedor,Total,Mediodepago from Venta ORDER BY ID ";
            System.out.println(consulta);
            try{stmt=con.createStatement();
                rs=stmt.executeQuery(consulta);
            }catch (Exception e){System.out.println ("error en la consulta");}
            ResultSetMetaData rsm = rs.getMetaData();
            int cantidadColumnas = rsm.getColumnCount();
            for(int i =1;i<=cantidadColumnas;i++)
            { modelo.addColumn(rsm.getColumnLabel(i));}
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            rs.close();
        }catch (Exception ex){ex.printStackTrace();}
        this.txtCodigo.setText("");
                        
             
                                                  

    }//GEN-LAST:event_btnVendedorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
          jt1.print(JTable.PrintMode.NORMAL);
      } catch (PrinterException ex) {
          Logger.getLogger(frmTablaEjemplo.class.getName()).log(Level.SEVERE, null, ex);
      }       
                                            
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.txtCodigo.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
          addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
        int eleccion = JOptionPane.showConfirmDialog(null, "Desea salir?");
        if ( eleccion == 0) {
            JOptionPane.showMessageDialog(null, "saliendo del sistema...");
            System.exit(0);
        }   
    }
});
    }//GEN-LAST:event_formWindowClosed

    private void btnMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarcaMouseClicked
        // TODO add your handling code here:
        this.txtCodigo.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jt1.getModel();
        modelo.setRowCount(0);
        jt1.updateUI();
    }//GEN-LAST:event_btnMarcaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentasBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentasBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentasBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentasBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentasBus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaPorClienteVenta;
    private javax.swing.JButton btnCodigoInterno;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnMedioDePago;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnSerieProducto;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JCalendarDemo jCalendarDemo1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
