/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.detalleVenta;
import Controlador.venta;
import Controlador.producto;
import Controlador.usuario;
import Controlador.venta;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author claudio
 */
public class frmVentas extends javax.swing.JFrame {
    //intanciacion de tabla 
DefaultTableModel tablita = new DefaultTableModel();
DefaultTableModel tablera = new DefaultTableModel();
DefaultTableModel tabla   = new DefaultTableModel();
DefaultListModel lista = new DefaultListModel();
producto miProducto = new producto();
private ResultSet rs = null;
private Statement stmt= null;
private ResultSetMetaData  rsm = null;
 private Connection con = null;
 public int acumulador=0;
  public String nombre;
  public   int precio=0;
  public  producto[] productosCargados  = new producto [1000];
  Container contenedor;
  public int resultado=0;
    private Component componentePadre;
    venta miVenta = new venta();
    producto P= new producto();
    public int Tot=0;
    public int valor=1;
    public float max=0;
    public float PrecioTotalFinal=0;
 
  
 
  /**
     * Creates new form frmVentaProducto
     */
    public frmVentas() {
        initComponents();
    //    this.lstInformacion.setModel(lista);
        setLocationRelativeTo(null);
        String datosCompra[]={"DESCRIPCION","PRECIO"};
         tabla.setColumnIdentifiers(datosCompra);
          this.jTable1.setModel(tabla);
          //CAPTURA LA FECHA DESDE EL ORDENADOR Y LA INTRODUCE TXTFECHA
          this.txtFecha2.setText(miProducto.getFechaactualizacion()); 
          //llenarcomboVendedor();
           llenarcomboPago();
           String fecha;
  Date fecha1 = new Date ();
  fecha = fecha1.toLocaleString();
  System.out.println(fecha);
  this.txtFecha2.setText(fecha);
 /*
  
     si se pasa a string
ya lo hice 
String fecha = new SimpleDateFormat("yyyy/MM/dd").format(jdcCalendarioEntrada.getDate());     
          
         
    */    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxVendedor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt2 = new javax.swing.JTable();
        mnuGrabar = new javax.swing.JButton();
        mnuFinalizarVenta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmdPago = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtNVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMontoDescuento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtFecha2 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PANTALLA DE VENTAS");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtPrecio.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel5.setText("Vendedor");

        cbxVendedor.setForeground(java.awt.Color.blue);
        cbxVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxVendedorMouseClicked(evt);
            }
        });
        cbxVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVendedorActionPerformed(evt);
            }
        });

        jt2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jt2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jt2.setEnabled(false);
        jt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt2);

        mnuGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/save.png"))); // NOI18N
        mnuGrabar.setText("GRABAR");
        mnuGrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuGrabarMouseClicked(evt);
            }
        });
        mnuGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGrabarActionPerformed(evt);
            }
        });

        mnuFinalizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/final.png"))); // NOI18N
        mnuFinalizarVenta.setText("Finalizar Venta");
        mnuFinalizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuFinalizarVentaMouseClicked(evt);
            }
        });
        mnuFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinalizarVentaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/atras3.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/escoba.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        jLabel6.setText("Pago");

        cmdPago.setForeground(java.awt.Color.blue);

        jLabel7.setText("Nro de Venta");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("FECHA/HORA");

        txtMontoDescuento.setEditable(false);
        txtMontoDescuento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMontoDescuento.setForeground(java.awt.Color.red);
        txtMontoDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMontoDescuentoMouseClicked(evt);
            }
        });

        jLabel9.setText("Subtotal");

        jLabel10.setText("Monto Descuento");

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSubtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSubtotalMouseClicked(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotal.setForeground(java.awt.Color.red);

        jLabel11.setText("TOTAL");

        jLabel12.setText("Detalles del producto");

        jLabel13.setText("Detalles de la Venta Actual");

        txtTipo.setEditable(false);

        txtCuenta.setEditable(false);
        txtCuenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCuenta.setForeground(java.awt.Color.red);
        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });

        jLabel3.setText("CANTIDAD DE ARTICULOS EN VENTA ACTUAL");

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setForeground(java.awt.Color.blue);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Documents\\NetBeansProjects\\sistemaDeVentas\\Master-Card-Blue-icon.png")); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Documents\\NetBeansProjects\\sistemaDeVentas\\American-Express-icon.png")); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\claudio\\Documents\\NetBeansProjects\\sistemaDeVentas\\Cirrus.png")); // NOI18N

        btnEliminar.setText("ELIMINAR PRODUCTO");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(414, 414, 414))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMontoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(mnuFinalizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mnuGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(143, 143, 143))
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtNVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(cmdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mnuGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtMontoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mnuFinalizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel14)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVendedorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxVendedorActionPerformed
    public void cargarProducto(){
    }
    
    private void llenarcomboPago(){
        this.cmdPago.removeAllItems();
        this.cmdPago.addItem("Seleccione..");
        this.cmdPago.addItem("Efectivo");
        this.cmdPago.addItem("Debito");
        this.cmdPago.addItem("Cheque");
  }
    private void NroBoleta(){
  boolean exito = true; int codigo = 0;
          
       
 
 }
         
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       framePrincipal formInicial = new framePrincipal();
        formInicial.setVisible(true);
        this.dispose();
      //frmPrincipal  = new frmPrincipal();
      
      
    }//GEN-LAST:event_jButton1MouseClicked

    private void cbxVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxVendedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVendedorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jt2MouseClicked

    private void txtMontoDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMontoDescuentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDescuentoMouseClicked

    private void txtSubtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSubtotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        this.txtCodigo.setText("");
       // this.txtCantidad.setText("");
       // this.txtFecha.setText("");
        this.txtMontoDescuento.setText("");
        this.txtSubtotal.setText("");
        this.txtMontoDescuento.setText("");
        this.txtPrecio.setText("");
        this.txtNVenta.setText("");
        this.txtTotal.setText("");
        this.txtPrecio.setText("");
        
        
        
    }//GEN-LAST:event_btnLimpiarMouseClicked
private void actualizarStock(String codigoBarra,int cantidad) throws SQLException{
      String conexion = "jdbc:odbc:venta";
        try {
     con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
        String serieProducto =this.txtCodigo.getText();
        String consultaStockactual="select stockactual as Total from producto where serieproducto='"+serieProducto+"'";
       try {stmt = con.createStatement();
        rs = stmt.executeQuery(consultaStockactual);
        } catch (Exception e) {System.out.println("error en la consulta: " + serieProducto);}
        try {
            while (rs.next()) {
                resultado = Integer.parseInt(rs.getString("Total"));
                
                System.out.println(resultado);
               
               
            }
           

       
         //   return true;
        } catch (SQLException ex) {
            //Logger.getLogger(nuevo3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    int exito=0;
      
        try {
     con= DriverManager.getConnection(conexion, "root","1234");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
       int stock=resultado-1;
       
     
      String sentenciaActualizacion = "update producto " +
             "set STOCKACTUAL="+stock +" where serieproducto = '"+ this.txtCodigo.getText()+"'";
            System.out.println(sentenciaActualizacion);
       try{ stmt=con.createStatement();
       exito = stmt.executeUpdate(sentenciaActualizacion);
     //  JOptionPane.showMessageDialog(this,"actualizado con exito");
       //this.txtCodigo.setText("");
       }
       catch(Exception e ){System.out.println("error en la actualizacion");}
       //de aqui
       
       
       
        
    
  stmt.close();
  con.close();
  stmt.close();
 }
   
    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
     
        int cantidad=1;
       
           if(this.txtCodigo.getText().equals("")){
       
       JOptionPane.showMessageDialog(this, "DEBES INGRESAR EL CODIGO A BUSCAR");
   }else{
    String codigoBarra =this.txtCodigo.getText();
   // int Cantidad  =     Integer.parseInt(txtCantidad.getText());
    
    int Cantidad=1;
     int valor1=0;
       int valor2=0;
    
      
       
         int valor=0;
         valor1=miProducto.getPrecioventa();
        miProducto.Buscar(codigoBarra);
         try {
             actualizarStock(codigoBarra,cantidad);
           miProducto.consultarStock(codigoBarra);
       } catch (SQLException ex) {
           Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
       }
       
         
         this.txtTipo.setText(miProducto.getTipo());
         this.txtPrecio.setText(""+miProducto.getPrecioventa());
       int n=0;
       int numero=0;
         
           this.lista.addElement(this.txtTipo.getText()+"    "+this.txtPrecio.getText());
           
           n=this.lista.getSize();
           System.out.println(n);
           this.txtCuenta.setText(""+n);
          //tabla
           int z=0;
           String Datos[]= new String[3];
           Datos[0]=this.txtTipo.getText();
           this.txtTipo.setText(null);
           Datos[1]=this.txtPrecio.getText();
           this.txtPrecio.setText(null);
           tabla.addRow(Datos);
           this.txtTipo.grabFocus();
           z = tabla.getRowCount();
        //   this.txtTotal.setText(""+z);
           
           
        

        
        
     
       
           try{      
        
   DefaultTableModel modelo = new DefaultTableModel();
   //this.jt1.setModel(vista);
   this.jt2.setModel(modelo);


   String conexion = "jdbc:odbc:venta";
           try {
        con= DriverManager.getConnection(conexion, "root","1234");
        } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
         String consulta = "select CODPRODUCTO AS CODIGO,MARCA,TIPO as DESCRIPCION,PRECIOVENTA as PRECIO_UNITARIO FROM PRODUCTO WHERE SERIEPRODUCTO='"+codigoBarra+"'";
      // System.out.println(consulta);
       try{stmt=con.createStatement();
       rs=stmt.executeQuery(consulta);
       }catch (Exception e){System.out.println ("error en la consulta");}
       ResultSetMetaData rsm = rs.getMetaData();
       int cantidadColumnas = rsm.getColumnCount();
       for(int i =1;i<=cantidadColumnas;i++)
       { modelo.addColumn(rsm.getColumnLabel(i));}
       while(rs.next()){
       Object[] fila = new Object[cantidadColumnas];
       for(int i = 0;i<cantidadColumnas;i++){
       fila[i]=rs.getObject(i+1);
       
      }
       modelo.addRow(fila);
       }
     while(rs.next()) { 
      nombre=rs.getString("tipo");
       precio=Integer.parseInt(rs.getString(""));
       
      
       listar(nombre,precio);
     }
      
   // rs.close();
   }catch (Exception ex){ex.printStackTrace();}
           
           
   }  
   String codigoBarra =this.txtCodigo.getText();
   String conexion = "jdbc:odbc:venta";
           try {
        con= DriverManager.getConnection(conexion, "root","1234");
        } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
         String consulta2 = "select PRECIOVENTA FROM PRODUCTO WHERE SERIEPRODUCTO='"+codigoBarra+"'";
          
       //System.out.println(consulta2);
       try{stmt=con.createStatement();
       rs=stmt.executeQuery(consulta2);
       }catch (Exception e){System.out.println ("error en la consulta");}
       
   int recueValor=0;
   //int cantidad2=Integer.parseInt(this.txtCantidad.getText());
   int cantidad2=1;
       try {
           while(rs.next()){
           int rescueValor = rs.getInt("PRECIOVENTA");
           calcular(rescueValor);
           this.txtCodigo.setText("");
             }
       } catch (SQLException ex) {
           Logger.getLogger(frmVentas.class.getName()).log(Level.SEVERE, null, ex);
       }
      
       
       
    
   
    }//GEN-LAST:event_txtCodigoActionPerformed
private void calcular(int rescueValor){
       acumulador=acumulador+rescueValor;
   //   JOptionPane.showMessageDialog(this,acumulador);
       this.txtSubtotal.setText(""+acumulador);
       Tot=acumulador-100;
       this.txtMontoDescuento.setText(""+100);
       this.txtTotal.setText(""+Tot);
       
      
 }

private void listar(String nombre,int precioventa) throws SQLException{
    miProducto.conectar();
        
        this.lista.addElement(nombre);
        this.lista.addElement(precio);
      
 }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         this.txtCodigo.requestFocusInWindow();
         this.txtTipo.setVisible(false);
         this.txtPrecio.setVisible(false);  
         conectar();
        DefaultComboBoxModel comboVendedor =  new DefaultComboBoxModel();
        this.cbxVendedor.setModel(comboVendedor);
       comboVendedor.removeAllElements();
        comboVendedor.addElement("Seleccione...");
        ArrayList<usuario> lista = new ArrayList();
        //String Sql="SELECT prov_codigo,prov_nombre FROM proveedor";
        String consultaCombo="select USUARIO from Usuario";
        try
        {
           stmt = con.createStatement();
            rs = stmt.executeQuery(consultaCombo);
            while(rs.next())
            { 
                comboVendedor.addElement(rs.getString("USUARIO"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error en la consulta ");
        }
        String consulta="select max(IDVENTA)as Total from venta";
        try
        {
           stmt = con.createStatement();
            rs = stmt.executeQuery(consulta);
            while(rs.next())
            { 
                int Numero=rs.getInt("Total");
                Tot=Numero+valor;
               this.txtNVenta.setText(""+Tot);
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error en la consulta ");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0'||c>'9'){evt.consume();}
            
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void mnuFinalizarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuFinalizarVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuFinalizarVentaMouseClicked

    private void mnuGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGrabarActionPerformed
       

    }//GEN-LAST:event_mnuGrabarActionPerformed
      private void limpiar(){
        this.txtCodigo.setText("");
        this.txtMontoDescuento.setText("");
        this.txtSubtotal.setText("");
        this.txtMontoDescuento.setText("");
        this.txtPrecio.setText("");
        this.txtNVenta.setText("");
        this.txtTotal.setText("");
        this.txtPrecio.setText("");
        this.txtCuenta.setText("");
        
        
      
 }
      public boolean conectar() {
         String conexion = "jdbc:odbc:venta";
        try {
     con= DriverManager.getConnection(conexion, "root","1234");
     System.out.println("CONECTADO EXITOSAMENTE");
     } catch (Exception e) {   JOptionPane.showMessageDialog(null,"no conecto");}
        
        return true;
        
        
    }
    private void mnuGrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuGrabarMouseClicked
         int codigo = 0,Total = 0,cliente=0,cantidad = 0;
        
      if(this.txtTotal.getText().equals("")||
        this.txtSubtotal.getText().equals(""))
      {JOptionPane.showMessageDialog(null,"NO HAY DATOS"); }
      else{
         
   try {
       String fecha;
  Date fecha1 = new Date ();
  fecha = fecha1.toLocaleString();
       int SubTotal = Integer.parseInt(this.txtSubtotal.getText());
            cantidad = Integer.parseInt(this.txtCuenta.getText());
       miVenta.setFechaVenta(fecha);
       if(cbxVendedor.getSelectedItem().equals("Seleccione..")||cmdPago.getSelectedItem().equals("Seleccione..")){
           JOptionPane.showMessageDialog(null, "ATENCION¡¡¡ NO SELECCIONO CAJA O MEDIO DE PAGO");
       }
       
       else{ 
       
       int  idCliente=Integer.parseInt(JOptionPane.showInputDialog(this,"ingrese cliente"));
        // String rut =JOptionPane.showInputDialog(this,"ingrese rut cliente");
       miVenta.setVendedor(this.cbxVendedor.getItemAt(this.cbxVendedor.getSelectedIndex()).toString());
        miVenta.setMedioDePago(this.cmdPago.getItemAt(this.cmdPago.getSelectedIndex()).toString());
        miVenta.setIdCliente(idCliente);
        
       if (miVenta.insertar()){
           detalleVenta miDetalle = new detalleVenta();
           miDetalle.setIdVenta(cliente);
           
            JOptionPane.showMessageDialog(null,"Venta Registrada Exitosamente");
            detalleVenta Detalle = new detalleVenta();
    int SubTotal2 = Integer.parseInt(this.txtSubtotal.getText());
           Detalle.setCantidad(cantidad);
           Detalle.setPrecio(SubTotal2);
              if(Detalle.insertar()){
              JOptionPane.showMessageDialog(null,"VentaDetalle Registrada Exitosamente");
              }
           
        }
       
       }
       miVenta.setTotal(SubTotal);
  }catch (Exception e){ System.out.println("debes ingresar numeros no letras");}}  
    }//GEN-LAST:event_mnuGrabarMouseClicked
   
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        
    }//GEN-LAST:event_formWindowClosed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     String codigo=JOptionPane.showInputDialog("LEER CODIGO A ELIMINAR");
      producto miProducto = new producto();
      
   int  subtotal = Integer.parseInt(this.txtSubtotal.getText());
        
        
        miProducto.conectar();
    int ResultadoFinal=0;
    String obtieneValores="select precioventa from producto where serieproducto="+codigo;
    try {stmt = con.createStatement();
        rs = stmt.executeQuery(obtieneValores);
        } catch (Exception e) {System.out.println("error en la consulta: " + codigo);}
        try {if (rs.next()) {
            // if(thi)
            int precio = rs.getInt("precioventa");
            ResultadoFinal=subtotal-precio;
            String valorTotal = Double.toString(ResultadoFinal);
            System.out.println(ResultadoFinal);
            
            this.txtTotal.setText(valorTotal);
           
        }
        
       }catch(Exception e){}
    
    
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void mnuFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinalizarVentaActionPerformed
        // TODO add your handling code here
        JOptionPane.showMessageDialog(this, "imprimiendo boleta");
    }//GEN-LAST:event_mnuFinalizarVentaActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cbxVendedor;
    private javax.swing.JComboBox cmdPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jt2;
    private javax.swing.JButton mnuFinalizarVenta;
    private javax.swing.JButton mnuGrabar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JFormattedTextField txtFecha2;
    private javax.swing.JTextField txtMontoDescuento;
    private javax.swing.JTextField txtNVenta;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
